config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  root "tops#index"
  resources :tops, only: :index
  resources :shops
  resources :study_tips
  resources :messages
end

app/models/shop.rb
class Shop < ApplicationRecord
  validates :name, presence: true
  validates :detail, presence: true

  has_one_attached :aicon_image
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:edit, :show]

  def index
    @shops = Shop.all
  end

  def new
    @shop = Shop.new
  end

  def create
    Shop.create(shop_params)
    redirect_to shops_path
  end

  def destroy
    shop = Shop.find(params[:id])
    shop.destroy
    redirect_to shops_path
  end

  def edit
  end

  def update
    shop = Shop.find(params[:id])
    shop.update(shop_params)
    redirect_to shops_path
  end

  def show
  end

  private

    def shop_params
      params.require(:shop).permit(:name, :aicon_image, :detail, :tel, :address, :url)
    end

    def set_shop
      @shop = Shop.find(params[:id])
    end

end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/edit.html.erb
<div class="register">
  <div class="register__form">
    <p class="register__form__title">Edit Shop</p>
    <%= form_with(model: @shop, local: true) do |f| %>
      <div class="register__form__name">
        <%= f.text_field :name, placeholder: "Name", size: "50", class: "register__form__name__label" %>
      </div>
      <div class="register__form__image">
        <%= f.file_field :aicon_image, placeholder: "Image", size: "50", class: "register__form__image__label" %>
      </div>
      <div class="register__form__detail">
        <%= f.text_area :detail, placeholder: "Detail", cols: "50", rows: "10", class: "register__form__detail__label" %>
      </div>
      <div class="register__form__tel">
        <%= f.text_field :tel, placeholder: "Tel Number", size: "50", class: "register__form__tel__label" %>
      </div>
      <div class="register__form__address">
        <%= f.text_field :address, placeholder: "Address", size: "50", class: "register__form__address__label" %>
      </div>
      <div class="register__form__url">
        <%= f.text_field :url, placeholder: "URL", size: "50", class: "register__form__url__label" %>
      </div>
      <div class="register__form__submit">
        <%= f.submit "SEND", class: "register__form__submit__label" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shops/index.html.erb
<div class="shops-index">
  <div id="app">
    <fade-in1>
      <div class="photo2">
        <div class="photo2__image">
          <%= image_tag "cafe2.webp", class: "photo2__image__el" %>
          <p class="photo2__image__ms">“If you’re not failing every now and again, it’s a sign you’re not doing anything very innovative.”</p>
          <p class="photo2__image__msn">Woody Allen</p>
        </div>
      </div>
    </fade-in1>
    <% @shops.each do |shop| %>
      <div class="content">
        <%= link_to shop_path(shop), class: "content__l" do %>
          <div class="content__l__name">
            <p class="content__l__name__title">
              <%= shop.name %>
            </p>
          </div>
          <div class="content__l__c">
            <%= image_tag shop.aicon_image, class: "content__l__c__image" %>
            <div class="content__l__c__detail">
              <%= simple_format(shop.detail) %>
            </div>
          </div>
        <% end %>
        <% if admin_signed_in? %>
          <div class="content__more">
            <ul class="content__more__ul">
              <li class="content__more__ul__li">
                <%= link_to 'edit', "/shops/#{shop.id}/edit", method: :get, class: "content__more__ul__li__el" %>
              </li>
              <li class="content__more__ul__li">
                <%= link_to 'delete', "/shops/#{shop.id}", method: :delete, class: "content__more__ul__li__el" %>
              </li>
            </ul>
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="shop-new">
      <% if admin_signed_in? %>
        <%= link_to 'new', new_shop_path, class: "shop-new__el" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shops/new.html.erb
<div class="register">
  <div class="register__form">
    <p class="register__form__title">New Shop</p>
    <%= form_with(model: @shop, local: true) do |f| %>
      <div class="register__form__name">
        <%= f.text_field :name, placeholder: "Name", size: "50", class: "register__form__name__label", id: "shop-name" %>
      </div>
      <div class="register__form__image">
        <%= f.file_field :aicon_image, placeholder: "Image", size: "50", class: "register__form__image__label", id: "shop-image" %>
      </div>
      <div class="register__form__detail">
        <%= f.text_area :detail, placeholder: "Detail", cols: "50", rows: "10", class: "register__form__detail__label", id: "shop-detail" %>
      </div>
      <div class="register__form__tel">
        <%= f.text_field :tel, placeholder: "Tel Number", size: "50", class: "register__form__tel__label", id: "shop-tel" %>
      </div>
      <div class="register__form__address">
        <%= f.text_field :address, placeholder: "Address", size: "50", class: "register__form__address__label", id: "shop-address" %>
      </div>
      <div class="register__form__url">
        <%= f.text_field :url, placeholder: "URL", size: "50", class: "register__form__url__label", id: "shop-url" %>
      </div>
      <div class="register__form__submit">
        <%= f.submit "SEND", class: "register__form__submit__label" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shops/show.html.erb
<div class="shop-show">
  <div class="content">
    <div class="content__image">
      <%= image_tag @shop.aicon_image, class: "content__image__el" %>
    </div>
    <div class="content__detail"><%= @shop.detail %></div>
    <div class="content__l">
      <div class="content__l__name"><%= @shop.name %></div>
      <div class="content__l__tel"><span class="content__l__tel--op">tel</span><%= @shop.tel %></div>
      <div class="content__l__address"><span class="content__l__address--op">address</span><%= @shop.address %></div>
      <div class="content__l__url"><span class="content__l__url--op">url</span><%= @shop.url %></div>
    </div>
  </div>
</div>