config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  root "tops#index"
  resources :tops, only: :index
  resources :shops
  resources :study_tips
  resources :messages
end

app/models/study_tip.rb
class StudyTip < ApplicationRecord
  validates :title, presence: true
  validates :detail, presence: true

  has_one_attached :image
end

app/controllers/study_tips_controller.rb
class StudyTipsController < ApplicationController

  def index
    @study_tips = StudyTip.all
  end

  def new
    @study_tip = StudyTip.new
  end

  def create
    StudyTip.create(study_tip_params)
    redirect_to study_tips_path
  end

  def destroy
    study_tip = StudyTip.find(params[:id])
    study_tip.destroy
    redirect_to study_tips_path
  end

  def edit
    @study_tip = StudyTip.find(params[:id])
  end

  def update
    study_tip = StudyTip.find(params[:id])
    study_tip.update(study_tip_params)
    redirect_to study_tips_path
  end

  private

    def study_tip_params
      params.require(:study_tip).permit(:title, :detail, :image)
    end

end

app/helpers/study_tips_helper.rb
module StudyTipsHelper
end

app/views/study_tips/edit.html.erb
<div class="register2">
  <div class="register2__form">
    <p class="register2__form__title">Edit Study_tip</p>
    <%= form_with(model: @study_tip, local: true) do |f| %>
      <div class="register2__form__name">
        <%= f.text_field :title, placeholder: "Tittle", size: "50", class: "register2__form__name__label" %>
      </div>
      <div class="register2__form__detail">
        <%= f.text_area :detail, placeholder: "Detail", cols: "50", rows: "10", class: "register2__form__name__label" %>
      </div>
      <div class="register2__form__image">
        <%= f.file_field :image, placeholder: "Image", size: "50", class: "register2__form__image__label" %>
      </div>
      <div class="register2__form__submit">
        <%= f.submit "SEND", class: "register2__form__submit__label" %>
      </div>
    <% end %>
  </div>
</div>

app/views/study_tips/index.html.erb
<div class="studytip">
  <div id="app">
    <fade-in1>
      <div class="photo3">
        <div class="photo3__image">
          <%= image_tag "cafe3.webp", class: "photo3__image__el" %>
          <p class="photo3__image__ms">“The greatest glory in living lies not in never falling, but in rising every time we fall.”</p>
          <p class="photo3__image__msn">Nelson Mandela</p>
        </div>
      </div>
    </fade-in1>
    <div class="content2">
      <% @study_tips.each do |study_tip| %>
        <h2 class="content2__title">
          <%= study_tip.title %>
        </h2>
        <div class="content2__c">
          <div>
            <%= image_tag study_tip.image, class: "content2__c__image" %>
          </div>
          <div class="content2__c__detail">
            <%= simple_format(study_tip.detail) %>
          </div>
        </div>
        <% if admin_signed_in? %>
          <div class="content2__more">
            <ul class="content2__more__ul">
              <li class="content2__more__ul__li">
                <%= link_to 'edit', "/study_tips/#{study_tip.id}/edit", method: :get, class: "content2__more__ul__li__el" %>
              </li>
              <li class="content2__more__ul__li">
                <%= link_to 'delete', "/study_tips/#{study_tip.id}", method: :delete, class: "content2__more__ul__li__el" %>
              </li>
            </ul>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="study-tip-new">
      <% if admin_signed_in? %>
        <%= link_to 'new', new_study_tip_path, class: "study-tip-new__el" %>
      <% end %>
    </div>
  </div>
</div>

app/views/study_tips/new.html.erb
<div class="register2">
  <div class="register2__form">
    <p class="register2__form__title">New Study_tip</p>
    <%= form_with(model: @study_tip, local: true) do |f| %>
      <div class="register2__form__name">
        <%= f.text_field :title, placeholder: "Tittle", size: "50", class: "register2__form__name__label", id: "study_tip-title" %>
      </div>
      <div class="register2__form__detail">
        <%= f.text_area :detail, placeholder: "Detail", cols: "50", rows: "10", class: "register2__form__name__label", id: "study_tip-detail" %>
      </div>
      <div class="register2__form__image">
        <%= f.file_field :image, placeholder: "Image", size: "50", class: "register2__form__image__label", id: "study_tip-image" %>
      </div>
      <div class="register2__form__submit">
        <%= f.submit "SEND", class: "register2__form__submit__label" %>
      </div>
    <% end %>
  </div>
</div>