config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  root "tops#index"
  resources :tops, only: :index
  resources :shops
  resources :study_tips
  resources :messages
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :password_confirmation, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :text, presence: true

  has_one_attached :image
end

app/models/shop.rb
class Shop < ApplicationRecord
  validates :name, presence: true
  validates :detail, presence: true

  has_one_attached :aicon_image
end

app/models/study_tip.rb
class StudyTip < ApplicationRecord
  validates :title, presence: true
  validates :detail, presence: true

  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :password_confirmation, presence: true
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    case resource
      when Admin then
        tops_path
      when User then
        messages_path
    end
  end

  def after_sign_out_path_for(resource)
    if resource == User
      messages_path
    else
      tops_path
    end
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.all.order(created_at: "DESC")
    @message = Message.new
  end

  def create
    Message.create(message_params)
    redirect_to messages_path
  end

  def destroy
    message = Message.find(params[:id])
    message.destroy
    redirect_to messages_path
  end

  private

    def message_params
      params.require(:message).permit(:text, :image)
    end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:edit, :show]

  def index
    @shops = Shop.all
  end

  def new
    @shop = Shop.new
  end

  def create
    Shop.create(shop_params)
    redirect_to shops_path
  end

  def destroy
    shop = Shop.find(params[:id])
    shop.destroy
    redirect_to shops_path
  end

  def edit
  end

  def update
    shop = Shop.find(params[:id])
    shop.update(shop_params)
    redirect_to shops_path
  end

  def show
  end

  private

    def shop_params
      params.require(:shop).permit(:name, :aicon_image, :detail, :tel, :address, :url)
    end

    def set_shop
      @shop = Shop.find(params[:id])
    end

end

app/controllers/study_tips_controller.rb
class StudyTipsController < ApplicationController

  def index
    @study_tips = StudyTip.all
  end

  def new
    @study_tip = StudyTip.new
  end

  def create
    StudyTip.create(study_tip_params)
    redirect_to study_tips_path
  end

  def destroy
    study_tip = StudyTip.find(params[:id])
    study_tip.destroy
    redirect_to study_tips_path
  end

  def edit
    @study_tip = StudyTip.find(params[:id])
  end

  def update
    study_tip = StudyTip.find(params[:id])
    study_tip.update(study_tip_params)
    redirect_to study_tips_path
  end

  private

    def study_tip_params
      params.require(:study_tip).permit(:title, :detail, :image)
    end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController

  def index
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/study_tips_helper.rb
module StudyTipsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Growool</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'hello_vue' %>
    <%# <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <h1 class="header__logo">
        <a href="/" class="header__logo--a">Growool</a>
      </h1>
      <nav class="header__wrap">
        <ul class="header__wrap__nav">
          <li class="header__wrap__nav__li">
            <%= link_to "shops", shops_path, class: "header__wrap__nav__li--a" %>
          </li>
          <li class="header__wrap__nav__li">
            <%= link_to "study_tips", study_tips_path, class: "header__wrap__nav__li--a" %>
          </li>
          <li class="header__wrap__nav__li">
            <%= link_to "messages", messages_path, class: "header__wrap__nav__li--a" %>
          </li>
          <li class="header__wrap__nav__li">
            <% if admin_signed_in? %>
              <%= link_to "sign-out", destroy_admin_session_path, method: :delete, class: "header__wrap__nav__li--a" %>
            <% else %>
              <%= link_to "admin", new_admin_session_path, class: "header__wrap__nav__li--a" %>
            <% end %>
          </li>
        </ul>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>